title: Privacy Guides
email: jonah@privacyguides.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.privacyguides.org" # the base hostname & protocol for your site, e.g. http://example.com
sass:
    sass_dir: _sass
excerpt_separator: <!--more-->
collections_dir: collections
collections:
  evergreen:
    output: true
    permalink: /:name/
  devices:
    output: true
    permalink: /devices/:path/
  software:
    output: true
    permalink: /software/:path/
  providers:
    output: true
    permalink: /providers/:path/
  posts:
    permalink: /blog/:year/:month/:day/:title/
  people:
    permalink: /blog/authors/:path/

build:
     date:
     time:

kramdown:
  auto_ids: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-brotli
exclude: [privacytools.io/]
