title: Privacy Guides
email: jonah@privacyguides.org
description: >- # this means to ignore newlines until "baseurl:"
  Massive organizations are monitoring your online activities.
  Privacy Guides is your central privacy and security resource to protect yourself online.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.privacyguides.org" # the base hostname & protocol for your site, e.g. http://example.com
sass:
    sass_dir: _sass
permalink: pretty
excerpt_separator: <!--more-->
collections_dir: collections
collections:
  evergreen:
    output: true
    permalink: /:slug/
  pages:
    output: true
    permalink: /:path/
  posts:
    permalink: /blog/:year/:month/:day/:title/
  people:
    permalink: /blog/authors/:path/

build:
     date:
     time:

kramdown:
  auto_ids: true

# Build settings
plugins:
  - jekyll-brotli
  - jekyll-sitemap
exclude: [privacytools.io/]
