project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true
files:
- source: "/docs/**/*.en.*"
  translation: "/docs/**/%file_name%.%two_letters_code%.%file_extension%"
  translation_replace:
    "en.": ""
- source: "/theme/overrides/*.en.html"
  translation: "/theme/overrides/%file_name%.%two_letters_code%.html"
  translation_replace:
    "en.": ""
- source: "/includes/*.en.md"
  translation: "/includes/%file_name%.%two_letters_code%.md"
  translation_replace:
    "en.": ""
