"preserve_hierarchy": true
files:
- source: "/docs/**/*.en.md"
  translation: "/docs/**/%file_name%.%locale_with_underscore%.md"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved
- source: "/theme/overrides/*.en.html"
  translation: "/theme/overrides/%file_name%.%locale_with_underscore%.html"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved
