docs_dir: 'docs'
site_url: "https://www.privacyguides.org/"
site_dir: 'site'

site_name: Privacy Guides
site_description: |
  Massive organizations are monitoring your online activities. Privacy Guides is your central privacy and security resource to protect yourself online.
copyright: |
  <b>Privacy Guides</b> is a non-profit, socially motivated website that provides information for protecting your data security and privacy.<br>
  We do not make money from recommending certain products, and we do not utilize affiliate links.<br>
  This content was made available by the Privacy Guides team and contributors. <a href="https://github.com/privacyguides/privacyguides">Get involved</a>!

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@privacyguides
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/privacy_guides
    - icon: fontawesome/brands/github
      link: https://github.com/privacyguides
    - icon: fontawesome/brands/reddit-alien
      link: https://reddit.com/r/PrivacyGuides
repo_url: https://github.com/privacyguides/privacyguides.org
repo_name: privacyguides.org
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: theme
  logo: assets/logo.svg
  favicon: assets/img/layout/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
watch:
  - theme

plugins:
  - i18n:
      default_language: en
      material_alternate: true
      languages:
        en:
          name: English
          build: false
  - tags
  - search
  - privacy:
      externals_exclude:
        - cdn.jsdelivr.net/npm/mathjax@3/* 
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - tables
  - footnotes
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js

nav:
  - Home: 'index.md'
  - 'Knowledge Base':
    - 'The Basics':
      - 'threat-modeling.md'
      - 'technology/dns.md'
      - 'security/multi-factor-authentication.md'
    - 'Mobile Devices':
      - 'android/overview.md'
      - 'android/security.md'
      - 'android/grapheneos-vs-calyxos.md'
    - 'Advanced':
      - 'setup/integrating-metadata-removal.md'
  - 'Recommendations':
    - 'tools.md'
    - 'Browsers':
      - 'browsers.md'
    - 'Operating Systems':
      - 'android.md'
      - 'linux-desktop.md'
      - 'qubes.md'
      - 'router.md'
    - 'Providers':
      - 'cloud.md'
      - 'dns.md'
      - 'email.md'
      - 'search-engines.md'
      - 'vpn.md'
    - 'Software':
      - 'calendar-contacts.md'
      - 'notebooks.md'
      - 'email-clients.md'
      - 'encryption.md'
      - 'file-sharing.md'
      - 'metadata-removal-tools.md'
      - 'multi-factor-authentication.md'
      - 'passwords.md'
      - 'productivity.md'
      - 'real-time-communication.md'
      - 'news-aggregators.md'
      - 'self-contained-networks.md'
      - 'video-streaming.md'
  - 'About Us':
    - 'about.md'
    - 'about/notices.md'
    - 'about/privacy-policy.md'
  - 'Discussions': 'https://github.com/orgs/privacyguides/discussions'
  - 'Blog': 'https://blog.privacyguides.org/'
