docs_dir: 'docs'
site_url: "https://www.privacyguides.org/"
site_dir: 'site'

site_name: Privacy Guides
site_description: |
  Privacy Guides is your central privacy and security resource to protect yourself online.
copyright: |
  <b>Privacy Guides</b> is a non-profit, socially motivated website that provides information for protecting your data security and privacy.<br>
  We do not make money from recommending certain products, and we do not use affiliate links.<br>
  &copy; 2022 Privacy Guides and contributors. <span class="twemoji"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><!--! Font Awesome Free 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc.--><path d="m245.83 214.87-33.22 17.28c-9.43-19.58-25.24-19.93-27.46-19.93-22.13 0-33.22 14.61-33.22 43.84 0 23.57 9.21 43.84 33.22 43.84 14.47 0 24.65-7.09 30.57-21.26l30.55 15.5c-6.17 11.51-25.69 38.98-65.1 38.98-22.6 0-73.96-10.32-73.96-77.05 0-58.69 43-77.06 72.63-77.06 30.72-.01 52.7 11.95 65.99 35.86zm143.05 0-32.78 17.28c-9.5-19.77-25.72-19.93-27.9-19.93-22.14 0-33.22 14.61-33.22 43.84 0 23.55 9.23 43.84 33.22 43.84 14.45 0 24.65-7.09 30.54-21.26l31 15.5c-2.1 3.75-21.39 38.98-65.09 38.98-22.69 0-73.96-9.87-73.96-77.05 0-58.67 42.97-77.06 72.63-77.06 30.71-.01 52.58 11.95 65.56 35.86zM247.56 8.05C104.74 8.05 0 123.11 0 256.05c0 138.49 113.6 248 247.56 248 129.93 0 248.44-100.87 248.44-248 0-137.87-106.62-248-248.44-248zm.87 450.81c-112.54 0-203.7-93.04-203.7-202.81 0-105.42 85.43-203.27 203.72-203.27 112.53 0 202.82 89.46 202.82 203.26-.01 121.69-99.68 202.82-202.84 202.82z"></path></svg></span><span class="twemoji"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><!--! Font Awesome Free 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc.--><path d="M314.9 194.4v101.4h-28.3v120.5h-77.1V295.9h-28.3V194.4c0-4.4 1.6-8.2 4.6-11.3 3.1-3.1 6.9-4.7 11.3-4.7H299c4.1 0 7.8 1.6 11.1 4.7 3.1 3.2 4.8 6.9 4.8 11.3zm-101.5-63.7c0-23.3 11.5-35 34.5-35s34.5 11.7 34.5 35c0 23-11.5 34.5-34.5 34.5s-34.5-11.5-34.5-34.5zM247.6 8C389.4 8 496 118.1 496 256c0 147.1-118.5 248-248.4 248C113.6 504 0 394.5 0 256 0 123.1 104.7 8 247.6 8zm.8 44.7C130.2 52.7 44.7 150.6 44.7 256c0 109.8 91.2 202.8 203.7 202.8 103.2 0 202.8-81.1 202.8-202.8.1-113.8-90.2-203.3-202.8-203.3z"></path></svg></span><span class="twemoji"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><!--! Font Awesome Free 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc.--><path d="M247.6 8C389.4 8 496 118.1 496 256c0 147.1-118.5 248-248.4 248C113.6 504 0 394.5 0 256 0 123.1 104.7 8 247.6 8zm.8 44.7C130.2 52.7 44.7 150.6 44.7 256c0 109.8 91.2 202.8 203.7 202.8 103.2 0 202.8-81.1 202.8-202.8.1-113.8-90.2-203.3-202.8-203.3zm94 144.3v42.5H162.1V197h180.3zm0 79.8v42.5H162.1v-42.5h180.3z"></path></svg></span> Content licensed under <a href="/about/"><strong>CC BY-ND 4.0</strong></a>.

extra:
  social:
    - icon: simple/matrix
      link: https://matrix.to/#/#privacyguides:matrix.org
      name: Matrix
    - icon: simple/discourse
      link: https://discuss.privacyguides.org/
      name: Forum
    - icon: simple/mastodon
      link: https://mastodon.neat.computer/@privacyguides
      name: Mastodon
    - icon: simple/twitter
      link: https://twitter.com/privacy_guides
      name: Twitter
    - icon: simple/github
      link: https://github.com/privacyguides
      name: GitHub
repo_url: https://github.com/privacyguides/privacyguides.org
repo_name: ""
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: theme
  logo: assets/brand/SVG/Logo/privacy-guides-logo-notext-colorbg.svg
  favicon: assets/brand/PNG/Favicon/favicon-32x32.png
  icon:
    repo: simple/github
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
  palette:
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - scheme: slate
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

watch:
  - theme
  - includes

plugins:
  i18n:
    default_language: en
    default_language_only: true
    material_alternate: true
    languages:
      en:
        name: English
        build: false
  tags: {}
  search: {}
  macros: {}

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.arithmatex:
    generic: true
  pymdownx.critic: {}
  pymdownx.caret: {}
  pymdownx.keys: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
  pymdownx.snippets:
    auto_append:
      - includes/abbreviations.en.md
  pymdownx.tasklist:
    custom_checkbox: true
  attr_list: {}
  def_list: {}
  md_in_html: {}
  meta: {}
  abbr: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      custom_icons:
        - theme/.icons
  tables: {}
  footnotes: {}
  toc:
    permalink: true
    toc_depth: 4

extra_css:
  - assets/stylesheets/extra.css?v=2.10.0
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/feedback.js

nav:
  - Home: 'index.md'
  - 'Knowledge Base':
    - 'basics/threat-modeling.md'
    - 'basics/common-threats.md'
    - 'basics/common-misconceptions.md'
    - 'basics/account-deletion.md'
    - 'Technology Essentials':
      - 'basics/passwords-overview.md'
      - 'basics/multi-factor-authentication.md'
      - 'basics/email-security.md'
      - 'basics/vpn-overview.md'
    - 'Operating Systems':
      - 'os/android-overview.md'
      - 'os/linux-overview.md'
    - 'Advanced Topics':
      - 'advanced/dns-overview.md'
      - 'advanced/tor-overview.md'
      - 'advanced/communication-network-types.md'
    - kb-archive.md
  - 'Recommendations':
    - 'tools.md'
    - 'Internet Browsing':
      - 'tor.md'
      - 'desktop-browsers.md'
      - 'mobile-browsers.md'
    - 'Operating Systems':
      - 'android.md'
      - 'linux-desktop.md'
      - 'qubes.md'
      - 'router.md'
    - 'Providers':
      - 'cloud.md'
      - 'dns.md'
      - 'email.md'
      - 'search-engines.md'
      - 'vpn.md'
    - 'Software':
      - 'calendar-contacts.md'
      - 'data-redaction.md'
      - 'email-clients.md'
      - 'encryption.md'
      - 'file-sharing.md'
      - 'frontends.md'
      - 'multi-factor-authentication.md'
      - 'news-aggregators.md'
      - 'notebooks.md'
      - 'passwords.md'
      - 'productivity.md'
      - 'real-time-communication.md'
      - 'video-streaming.md'
  - 'About':
    - 'about/index.md'
    - 'about/criteria.md'
    - 'about/statistics.md'
    - 'about/notices.md'
    - 'about/privacy-policy.md'
    - 'Community':
      - 'about/donate.md'
      - 'Online Services': 'about/services.md'
      - 'Code of Conduct': 'CODE_OF_CONDUCT.md'
      - 'about/privacytools.md'
    - 'Contributing':
      - 'Writing Guides':
        - 'meta/writing-style.md'
        - 'meta/brand.md'
      - 'Technical Guides':
        - 'meta/uploading-images.md'
        - 'meta/git-recommendations.md'
  - 'Donate': '/about/donate/'
  - 'Forum': 'https://discuss.privacyguides.org/'
  - 'Blog': 'https://blog.privacyguides.org/'
