docs_dir: 'docs'
site_url: "https://www.privacyguides.org/"
site_dir: 'site'

site_name: Privacy Guides

extra:
  social:
    - icon: simple/mastodon
      link: https://mastodon.neat.computer/@privacyguides
      name: Mastodon
    - icon: simple/matrix
      link: https://matrix.to/#/#privacyguides:matrix.org
      name: Matrix
    - icon: simple/discourse
      link: https://discuss.privacyguides.net/
      name: Forum
    - icon: simple/github
      link: https://github.com/privacyguides
      name: GitHub
repo_url: https://github.com/privacyguides/privacyguides.org
repo_name: ""
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: theme
  logo: assets/brand/SVG/Logo/privacy-guides-logo-notext-colorbg.svg
  favicon: assets/brand/PNG/Favicon/favicon-32x32.png
  icon:
    repo: simple/github
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
  palette:
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode
    - scheme: slate
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

watch:
  - theme
  - includes

plugins:
  i18n:
    default_language: en
    material_alternate: true
    languages:
      en:
        name: English
        build: false # should be disabled to avoid duplicate /en/ pages
      bn:
        name: bn
        build: false
      es:
        name: es
        build: false
      fr:
        name: Français
        build: true
      he:
        name: עִברִית
        build: true
      hu:
        name: hu
        build: false
      it:
        name: it
        build: false
      nl:
        name: Nederlands
        build: true
      pt:
        name: pt
        build: false
      ru:
        name: ru
        build: false
      tr:
        name: tr
        build: false
      uk:
        name: uk
        build: false
      zh:
        name: zh
        build: false
    nav_translations:
      he:
        'Home': 'דף הבית'
        'Knowledge Base': 'ידע בסיסי'
        'Technology Essentials': 'יסודות הטכנולוגיה'
        'Operating Systems': 'מערכות הפעלה'
        'Advanced Topics': 'נושאים מתקדמים'
        'Recommendations': 'המלצות'
        'Internet Browsing': 'גלישה באינטרנט'
        'Providers': 'ספקים'
        'Software': 'תוכנה'
        'About': 'על אודות'
        'Changelog': 'יומן שינויים'
        'Forum': 'פורום'
        'Blog': 'בלוג'
      fr:
        'Home': 'Accueil'
        'Knowledge Base': 'Base de connaissances'
        'Technology Essentials': 'Les essentiels de la technologie'
        'Operating Systems': "Systèmes d'exploitation"
        'Advanced Topics': 'Sujets avancés'
        'Recommendations': 'Recommandations'
        'Internet Browsing': 'Navigation internet'
        'Providers': 'Fournisseurs'
        'Software': 'Logiciels'
        'About': 'À propos'
        'Changelog': 'Journal des modifications'
        'Forum': 'Forum'
        'Blog': 'Blog'
      nl:
        'Home': 'Home'
        'Knowledge Base': 'Kennisbank'
        'Technology Essentials': 'Technologie essenties'
        'Operating Systems': 'Besturings systemen'
        'Advanced Topics': 'Gevorderde onderwerpen'
        'Recommendations': 'Recommendaties'
        'Internet Browsing': 'Surfen op het internet'
        'Providers': 'Providers'
        'Software': 'Software'
        'About': 'Over ons'
        'Changelog': 'Changelog'
        'Forum': 'Forum'
        'Blog': 'Blog'
  tags: {}
  search: {}
  macros: {}

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.arithmatex:
    generic: true
  pymdownx.critic: {}
  pymdownx.caret: {}
  pymdownx.keys: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
  pymdownx.snippets:
    auto_append:
      - includes/abbreviations.en.txt
  pymdownx.tasklist:
    custom_checkbox: true
  attr_list: {}
  def_list: {}
  md_in_html: {}
  meta: {}
  abbr: {}
  pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      custom_icons:
        - theme/.icons
  tables: {}
  footnotes: {}
  toc:
    permalink: true
    toc_depth: 4

extra_css:
  - assets/stylesheets/extra.css?v=2.10.0
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/feedback.js

nav:
  - Home: 'index.md'
  - 'Knowledge Base':
    - 'basics/threat-modeling.md'
    - 'basics/common-threats.md'
    - 'basics/common-misconceptions.md'
    - 'basics/account-creation.md'
    - 'basics/account-deletion.md'
    - 'Technology Essentials':
      - 'basics/passwords-overview.md'
      - 'basics/multi-factor-authentication.md'
      - 'basics/email-security.md'
      - 'basics/vpn-overview.md'
    - 'Operating Systems':
      - 'os/android-overview.md'
      - 'os/linux-overview.md'
      - 'os/qubes-overview.md'
    - 'Advanced Topics':
      - 'advanced/dns-overview.md'
      - 'advanced/tor-overview.md'
      - 'advanced/communication-network-types.md'
    - kb-archive.md
  - 'Recommendations':
    - 'tools.md'
    - 'Internet Browsing':
      - 'tor.md'
      - 'desktop-browsers.md'
      - 'mobile-browsers.md'
    - 'Operating Systems':
      - 'android.md'
      - 'desktop.md'
      - 'router.md'
    - 'Providers':
      - 'cloud.md'
      - 'dns.md'
      - 'email.md'
      - 'search-engines.md'
      - 'vpn.md'
    - 'Software':
      - 'calendar.md'
      - 'data-redaction.md'
      - 'email-clients.md'
      - 'encryption.md'
      - 'file-sharing.md'
      - 'frontends.md'
      - 'multi-factor-authentication.md'
      - 'news-aggregators.md'
      - 'notebooks.md'
      - 'passwords.md'
      - 'productivity.md'
      - 'real-time-communication.md'
      - 'video-streaming.md'
  - 'About':
    - 'about/index.md'
    - 'about/criteria.md'
    - 'about/statistics.md'
    - 'about/notices.md'
    - 'about/privacy-policy.md'
    - 'Community':
      - 'about/donate.md'
      - 'Online Services': 'about/services.md'
      - 'Code of Conduct': 'CODE_OF_CONDUCT.md'
      - 'about/privacytools.md'
    - 'Contributing':
      - 'Writing Guides':
        - 'meta/writing-style.md'
        - 'meta/brand.md'
      - 'Technical Guides':
        - 'meta/uploading-images.md'
        - 'meta/git-recommendations.md'
  - 'Changelog': 'https://github.com/privacyguides/privacyguides.org/releases'
  - 'Forum': 'https://discuss.privacyguides.net/'
  - 'Blog': 'https://blog.privacyguides.org/'
