INHERIT: mkdocs-common.yml

plugins:
  macros: {}
  meta: {}
  git-committers:
    enabled: !ENV [GITCOMMITTERS, PRODUCTION, NETLIFY, false]
    repository: privacyguides/privacyguides.org
    branch: main
  git-revision-date-localized:
    enabled: !ENV [GITREVISIONDATE, PRODUCTION, NETLIFY, false]
    exclude:
      - index.md
    fallback_to_build_date: true
  optimize:
    enabled: !ENV [OPTIMIZE, PRODUCTION, NETLIFY, false]
  typeset: {}
  social:
    cards: !ENV [CARDS, PRODUCTION, NETLIFY, true]
    cards_dir: assets/img/social
    cards_layout_dir: config/layouts
    cards_layout: page
    # cards_layout: pride

markdown_extensions:
  material.extensions.preview:
    sources:
      exclude:
        - tools.md
