name: Build Website
on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python runtime
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Cache files
        uses: actions/cache@v3.0.2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Build website
        run: |
          mkdocs build
          mv .well-known site/
          tar cvf site.tar site
          mkdocs --version

      - name: Package website
        uses: actions/upload-artifact@v3
        with:
          name: generated-site
          path: site.tar
