# Copyright (c) 2024 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: Build Website

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repo:
        required: true
        type: string
      lang:
        required: true
        type: string
      i18n:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.i18n }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.ref }}
          persist-credentials: 'false'

      - uses: actions/download-artifact@v4
        with:
          path: modules

      - run: |
          rmdir modules/mkdocs-material
          mv modules/mkdocs-material-insiders modules/mkdocs-material
          rmdir theme/assets/brand
          mv modules/brand theme/assets/brand

      - if: inputs.i18n
        run: |
          cp -rl modules/i18n/i18n .
          cp -rl modules/i18n/includes .
          cp -rl modules/i18n/theme .

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: 'pipenv'

      - name: Cache files
        uses: actions/cache@v4.0.2
        with:
          key: ${{ inputs.ref }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install
          sudo apt install pngquant

      - name: Build website
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARDS: false
          CONTEXT: deploy-preview
          NETLIFY: true
        run: |
          pipenv run mkdocs build --config-file config/mkdocs.${{ inputs.lang }}.yml
          cp -r static/* site/
          pipenv run mkdocs --version
          tar -czvf site-build-${{ inputs.lang }}.tar.gz site

      - name: Upload tar.gz file
        uses: actions/upload-artifact@v4
        with:
          name: site-build-${{ inputs.lang }}.tar.gz
          path: site-build-${{ inputs.lang }}.tar.gz
