# Copyright (c) 2022-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: 🛠️ Deploy to GitHub Pages

on:
  workflow_dispatch:
  release:
    types: [published]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  PYTHON_VERSION: 3.8

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}
          submodules: 'true'
      
      - name: Pages setup
        uses: actions/configure-pages@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Cache files
        uses: actions/cache@v3.3.1
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install

      - name: Build website
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARDS: true
        run: |
          pipenv run mkdocs build --config-file config/mkdocs.en.yml
          pipenv run mkdocs --version

      - name: Package website
        uses: actions/upload-pages-artifact@v2
        with:
          path: site

  deploy:
    name: Deploy
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
